// frontend/src/components/TranslatePanel.vue
<template>
  <div class="translate-panel card">
    <div class="panel-main">
      <!-- 步骤 1-2：上传与配置 -->
      <div class="config-section" v-if="!taskRunning && !result && !errorMessage">
        <div class="section-title">
          <span class="step-chip">1</span>
          <h2>上传漫画图片</h2>
        </div>

        <div
          class="drop-zone"
          :class="{ 'is-dragging': isDragging, 'has-file': !!file }"
          @dragover.prevent="isDragging = true"
          @dragleave.prevent="isDragging = false"
          @drop.prevent="onDrop"
          @click="triggerFileInput"
          role="button"
          :aria-label="'上传图片，支持格式 ' + allowedExts"
          tabindex="0"
          @keydown.enter.prevent="triggerFileInput"
          @keydown.space.prevent="triggerFileInput"
        >
          <input
            ref="fileInput"
            type="file"
            accept=".jpg,.jpeg,.png,.webp,.bmp"
            class="hidden-input"
            @change="onFileSelect"
          />

          <template v-if="!file">
            <div class="drop-icon" aria-hidden="true">
              <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <path d="m17 8-5-5-5 5"/>
                <path d="M12 3v12"/>
              </svg>
            </div>
            <p class="drop-title">点击上传，或拖拽图片到此处</p>
            <p class="drop-hint">支持 JPG / PNG / WebP / BMP，单张不超过 10MB</p>
          </template>

          <template v-else>
            <div class="file-preview">
              <img :src="filePreviewUrl" alt="待翻译图片预览" />
              <div class="file-meta">
                <strong class="file-name">{{ file.name }}</strong>
                <span class="file-size">{{ formatBytes(file.size) }}</span>
              </div>
              <button
                class="btn btn-ghost remove-btn"
                type="button"
                @click.stop="clearFile"
                aria-label="移除图片"
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M18 6 6 18M6 6l12 12"/></svg>
              </button>
            </div>
          </template>
        </div>

        <p v-if="fileError" class="field-error" role="alert">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 8v5"/><path d="M12 16h.01"/></svg>
          {{ fileError }}
        </p>

        <div class="section-title spaced">
          <span class="step-chip">2</span>
          <h2>选择翻译语言</h2>
        </div>

        <div class="lang-row">
          <div class="form-group lang-group">
            <label class="form-label" for="source-lang">源语言</label>
            <select id="source-lang" v-model="sourceLang" class="form-select">
              <option value="ja">日语</option>
              <option value="en">英语</option>
            </select>
          </div>

          <div class="lang-swap" aria-hidden="true">
            <button class="swap-btn" type="button" @click="swapLangs" aria-label="交换语言方向" tabindex="-1">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M7 16V4m0 0L3 8m4-4 4 4"/>
                <path d="M17 8v12m0 0 4-4m-4 4-4-4"/>
              </svg>
            </button>
          </div>

          <div class="form-group lang-group">
            <label class="form-label" for="target-lang">目标语言</label>
            <select id="target-lang" v-model="targetLang" class="form-select">
              <option value="zh">中文</option>
            </select>
          </div>
        </div>

        <div class="action-row">
          <button
            class="btn btn-primary btn-translate"
            :disabled="!file || !canSubmit"
            @click="startTranslate"
          >
            <svg v-if="!submitting" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <path d="m12 3 5 5-5 5M5 8h12M7 14l-2 7"/>
            </svg>
            <span v-if="submitting">正在提交…</span>
            <span v-else>开始翻译</span>
          </button>
        </div>
      </div>

      <!-- 步骤 3：翻译进度 -->
      <div class="progress-section" v-else-if="taskRunning">
        <div class="progress-header">
          <span class="spinner" aria-hidden="true"></span>
          <h2>正在翻译漫画…</h2>
        </div>
        <p class="progress-file">{{ file.name }}</p>

        <div class="progress-track" role="progressbar" :aria-valuenow="overallProgress" aria-valuemin="0" aria-valuemax="100" aria-label="翻译进度">
          <div class="progress-fill" :style="{ width: overallProgress + '%' }"></div>
        </div>
        <div class="progress-percent">{{ overallProgress }}%</div>

        <ol class="step-list">
          <li
            v-for="step in stepList"
            :key="step.key"
            class="step-item"
            :class="{ done: step.done, active: step.active }"
          >
            <span class="step-dot" aria-hidden="true">
              <svg v-if="step.done" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>
            </span>
            <span class="step-label">{{ step.label }}</span>
            <span class="step-percent" v-if="step.active">{{ step.percent }}%</span>
          </li>
        </ol>

        <button class="btn btn-ghost btn-cancel" @click="cancelTask">
          取消翻译
        </button>
      </div>

      <!-- 结果展示 -->
      <div class="result-section" v-else-if="result">
        <div class="result-header">
          <div>
            <h2>翻译完成</h2>
            <p class="result-meta">
              共识别 {{ result.textCount || 0 }} 处文字
              <template v-if="result.durationMs"> · 耗时 {{ formatDuration(result.durationMs) }}</template>
            </p>
          </div>
          <a class="btn btn-primary" :href="result.resultUrl" download :aria-label="'下载翻译结果 ' + file.name">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10 5 5 5-5"/><path d="M12 15V3"/></svg>
            下载图片
          </a>
        </div>

        <div class="compare-grid">
          <figure class="compare-item">
            <figcaption class="compare-label">原图</figcaption>
            <div class="image-frame">
              <img :src="result.originalUrl" :alt="'原图 ' + file.name" loading="lazy" />
            </div>
          </figure>
          <figure class="compare-item">
            <figcaption class="compare-label compare-label-result">
              <span class="result-tag">译后</span>
            </figcaption>
            <div class="image-frame">
              <img :src="result.resultUrl" :alt="'翻译结果 ' + file.name" loading="lazy" />
            </div>
          </figure>
        </div>

        <div class="result-actions">
          <button class="btn btn-secondary" @click="resetAll">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5"/></svg>
            翻译下一张
          </button>
        </div>
      </div>

      <!-- 失败态 -->
      <div class="error-section" v-else-if="errorMessage">
        <div class="error-icon" aria-hidden="true">
          <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 8v5"/><path d="M12 16h.01"/></svg>
        </div>
        <h2>翻译失败</h2>
        <p class="error-text">{{ errorMessage }}</p>
        <p v-if="isBlurHint" class="error-hint">建议：尝试更换更清晰、对比度更高的图片。</p>
        <div class="error-actions">
          <button class="btn btn-primary" @click="resetAll">重新上传</button>
          <button class="btn btn-secondary" @click="retryTask">重试</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import {
  createTranslateTask,
  getTaskStatus,
  getTaskResultUrl,
  deleteTask,
  formatBytes,
  formatDuration,
} from '../api'

const emit = defineEmits(['notify'])

const STEPS = [
  { key: 'detect', label: '检测文本区域' },
  { key: 'ocr', label: '识别文字' },
  { key: 'translate', label: '翻译内容' },
  { key: 'inpaint', label: '修复图像' },
  { key: 'render', label: '渲染译文' },
]
const STEP_ORDER = STEPS.map((s) => s.key)

const allowedExts = '.jpg,.jpeg,.png,.webp,.bmp'
const MAX_MB = 10

const fileInput = ref(null)
const file = ref(null)
const filePreviewUrl = ref('')
const fileError = ref('')
const sourceLang = ref('ja')
const targetLang = ref('zh')
const isDragging = ref(false)

const taskId = ref(null)
const taskRunning = ref(false)
const submitting = ref(false)
const currentStep = ref('')
const stepProgress = ref({})
const errorMessage = ref('')
const result = ref(null)

let pollTimer = null

const canSubmit = computed(() => !!file.value && !fileError.value)

function validateFile(f) {
  if (!f) return '请选择图片文件'
  const ext = (f.name.split('.').pop() || '').toLowerCase()
  if (!allowedExts.includes(`.${ext}`)) return `不支持 .${ext} 格式，仅支持 JPG / PNG / WebP / BMP`
  if (f.size > MAX_MB * 1024 * 1024) return `文件超过 ${MAX_MB}MB 限制，请压缩后重试`
  if (f.size === 0) return '文件为空'
  if (!f.type.startsWith('image/')) return '请上传图片文件'
  return ''
}

function setFile(f) {
  const err = validateFile(f)
  fileError.value = err
  if (err) {
    file.value = null
    filePreviewUrl.value = ''
    return false
  }
  file.value = f
  filePreviewUrl.value = URL.createObjectURL(f)
  return true
}

function onFileSelect(e) {
  const f = e.target.files?.[0]
  if (f) setFile(f)
  e.target.value = ''
}

function onDrop(e) {
  isDragging.value = false
  const f = e.dataTransfer.files?.[0]
  if (f) setFile(f)
}

function triggerFileInput() {
  fileInput.value?.click()
}

function clearFile() {
  file.value = null
  filePreviewUrl.value = ''
  fileError.value = ''
}

function swapLangs() {
  if (sourceLang.value === 'zh') return
  const tmp = sourceLang.value
  sourceLang.value = targetLang.value === 'zh' ? (tmp === 'ja' ? 'en' : 'ja') : targetLang.value
  targetLang.value = tmp === 'zh' ? (targetLang.value === 'ja' ? 'zh' : 'zh') : tmp
}

const stepList = computed(() => {
  const currentIdx = STEP_ORDER.indexOf(currentStep.value)
  return STEPS.map((s, i) => ({
    ...s,
    done: i < currentIdx || (i === currentIdx && stepProgress.value[s.key] >= 100),
    active: i === currentIdx && stepProgress.value[s.key] < 100,
    percent: stepProgress.value[s.key] || 0,
  }))
})

const overallProgress = computed(() => {
  if (!currentStep.value) return 0
  const idx = STEP_ORDER.indexOf(currentStep.value)
  const doneWeight = idx / STEP_ORDER.length
  const curWeight = (stepProgress.value[currentStep.value] || 0) / 100 / STEP_ORDER.length
  return Math.min(99, Math.round((doneWeight + curWeight) * 100))
})

function startTranslate() {
  if (!file.value) return
  const f = file.value
  submitting.value = true
  fileError.value = ''
  errorMessage.value = ''
  result.value = null

  createTranslateTask(f, sourceLang.value, targetLang.value)
    .then((data) => {
      taskId.value = data.task_id
      taskRunning.value = true
      submitting.value = false
      currentStep.value = 'detect'
      stepProgress.value = {}
      startPolling()
    })
    .catch((err) => {
      submitting.value = false
      errorMessage.value = err.message
      emit('notify', err.message, 'error')
    })
}

function startPolling() {
  stopPolling()
  pollTimer = setInterval(pollStatus, 800)
  pollStatus()
}

function stopPolling() {
  if (pollTimer) {
    clearInterval(pollTimer)
    pollTimer = null
  }
}

async function pollStatus() {
  if (!taskId.value) return
  try {
    const status = await getTaskStatus(taskId.value)
    currentStep.value = status.step || currentStep.value
    stepProgress.value[currentStep.value] = Math.max(stepProgress.value[currentStep.value] || 0, status.progress)
    // 计算步骤内进度
    if (status.step) {
      const idx = STEP_ORDER.indexOf(status.step)
      if (idx > 0) {
        const prevDone = idx
        const stepBase = (prevDone / STEP_ORDER.length) * 100
        const stepShare = ((status.progress - stepBase) / (100 / STEP_ORDER.length)) * 100
        stepProgress.value[status.step] = Math.min(100, Math.max(0, Math.round(stepShare)))
      }
    }

    if (status.status === 'completed') {
      stopPolling()
      taskRunning.value = false
      result.value = {
        resultUrl: getTaskResultUrl(taskId.value),
        originalUrl: filePreviewUrl.value,
        textCount: status.text_count,
        durationMs: status.duration_ms,
      }
      emit('notify', '翻译完成！', 'success')
    } else if (status.status === 'failed') {
      stopPolling()
      taskRunning.value = false
      errorMessage.value = status.error || '翻译失败，请重试'
      emit('notify', errorMessage.value, 'error')
    }
  } catch (err) {
    // 网络抖动时继续轮询，多次失败则提示
    stopPolling()
    taskRunning.value = false
    errorMessage.value = err.message
    emit('notify', '获取进度失败：' + err.message, 'error')
  }
}

const isBlurHint = computed(() => (errorMessage.value || '').includes('模糊'))

function cancelTask() {
  stopPolling()
  if (taskId.value) {
    deleteTask(taskId.value).catch(() => {})
  }
  taskRunning.value = false
  resetAll()
}

function retryTask() {
  resetAll()
  setTimeout(() => startTranslate(), 50)
}

function resetAll() {
  stopPolling()
  taskId.value = null
  taskRunning.value = false
  submitting.value = false
  currentStep.value = ''
  stepProgress.value = {}
  errorMessage.value = ''
  result.value = null
}

onUnmounted(() => {
  stopPolling()
  if (filePreviewUrl.value) URL.revokeObjectURL(filePreviewUrl.value)
})

defineExpose({ refresh: () => {} })
</script>

<style scoped>
.translate-panel {
  max-width: 860px;
  margin: 0 auto;
  padding: var(--space-6);
  animation: fade-in var(--duration-base) var(--ease);
}

.hidden-input {
  display: none;
}

.section-title {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  margin-bottom: var(--space-4);
}

.section-title.spaced {
  margin-top: var(--space-6);
}

.step-chip {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: var(--radius-full);
  background: var(--brand-600);
  color: #fff;
  font-size: 14px;
  font-weight: 700;
  flex-shrink: 0;
}

.section-title h2 {
  font-size: 19px;
}

.drop-zone {
  border: 2px dashed var(--border);
  border-radius: var(--radius-lg);
  padding: var(--space-7) var(--space-5);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  cursor: pointer;
  transition: all var(--duration-base) var(--ease);
  background: var(--surface-1);
  min-height: 200px;
}

.drop-zone:hover,
.drop-zone:focus-visible {
  border-color: var(--brand-400);
  background: var(--brand-50);
}

.drop-zone.is-dragging {
  border-color: var(--brand-500);
  background: var(--brand-50);
  transform: scale(1.01);
}

.drop-icon {
  color: var(--brand-400);
  margin-bottom: var(--space-3);
}

.drop-title {
  font-size: 16px;
  font-weight: 600;
  color: var(--ink-700);
}

.drop-hint {
  font-size: 13px;
  color: var(--ink-500);
  margin-top: var(--space-2);
}

/* 文件预览 */
.file-preview {
  display: flex;
  align-items: center;
  gap: var(--space-4);
  width: 100%;
  max-width: 480px;
}

.file-preview img {
  width: 88px;
  height: 88px;
  object-fit: cover;
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-sm);
  border: 1px solid var(--border);
}

.file-meta {
  display: flex;
  flex-direction: column;
  text-align: left;
  flex: 1;
  min-width: 0;
}

.file-name {
  font-size: 15px;
  color: var(--ink-900);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.file-size {
  font-size: 13px;
  color: var(--ink-500);
}

.remove-btn {
  align-self: flex-start;
  flex-shrink: 0;
  min-height: 36px;
}

.lang-row {
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  gap: var(--space-3);
  align-items: end;
}

.lang-swap {
  display: flex;
  align-items: center;
  padding-bottom: 12px;
}

.swap-btn {
  border: 1px solid var(--border);
  background: var(--surface-0);
  width: 40px;
  height: 40px;
  border-radius: var(--radius-full);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  color: var(--ink-500);
  transition: all var(--duration-fast) var(--ease);
}

.swap-btn:hover {
  color: var(--brand-600);
  border-color: var(--brand-400);
  transform: rotate(180deg);
}

.action-row {
  display: flex;
  justify-content: center;
  margin-top: var(--space-6);
}

.btn-translate {
  min-width: 200px;
  padding: 14px 32px;
  font-size: 16px;
}

/* 进度 */
.progress-section {
  padding: var(--space-4) var(--space-2);
  text-align: center;
}

.progress-header {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-3);
}

.progress-header h2 {
  font-size: 20px;
}

.progress-file {
  color: var(--ink-500);
  font-size: 14px;
  margin-top: var(--space-2);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.spinner {
  width: 26px;
  height: 26px;
  border: 3px solid var(--brand-200);
  border-top-color: var(--brand-600);
  border-radius: 50%;
  animation: spin 0.9s linear infinite;
  flex-shrink: 0;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.progress-track {
  margin-top: var(--space-6);
  height: 10px;
  background: var(--surface-2);
  border-radius: var(--radius-full);
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: linear-gradient(90deg, var(--brand-500), var(--brand-600));
  border-radius: var(--radius-full);
  transition: width var(--duration-base) var(--ease);
}

.progress-percent {
  margin-top: var(--space-2);
  font-size: 14px;
  font-weight: 700;
  color: var(--brand-600);
}

.step-list {
  list-style: none;
  margin-top: var(--space-6);
  display: grid;
  gap: var(--space-2);
  text-align: left;
  max-width: 480px;
  margin-left: auto;
  margin-right: auto;
}

.step-item {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  padding: 10px 14px;
  border-radius: var(--radius-md);
  background: var(--surface-1);
  color: var(--ink-500);
  transition: all var(--duration-fast) var(--ease);
}

.step-item.active {
  background: var(--brand-50);
  color: var(--brand-700);
}

.step-item.done {
  background: #ecfdf5;
  color: var(--success-500);
}

.step-dot {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 22px;
  height: 22px;
  border-radius: var(--radius-full);
  background: var(--surface-2);
  flex-shrink: 0;
}

.step-item.active .step-dot {
  background: var(--brand-200);
  animation: pulse 1.5s var(--ease) infinite;
}

@keyframes pulse {
  0%, 100% {
    box-shadow: 0 0 0 0 rgba(99, 102, 241, 0.3);
  }
  50% {
    box-shadow: 0 0 0 6px rgba(99, 102, 241, 0);
  }
}

.step-item.done .step-dot {
  background: var(--success-500);
  color: #fff;
}

.step-label {
  flex: 1;
  font-size: 14px;
  font-weight: 500;
}

.step-percent {
  font-size: 13px;
  font-weight: 600;
}

.btn-cancel {
  margin-top: var(--space-6);
}

/* 结果 */
.result-section {
  padding: var(--space-2);
}

.result-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-4);
  flex-wrap: wrap;
  margin-bottom: var(--space-5);
}

.result-header h2 {
  font-size: 22px;
}

.result-meta {
  color: var(--ink-500);
  font-size: 14px;
  margin-top: 4px;
}

.compare-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--space-4);
}

.compare-label {
  font-size: 14px;
  font-weight: 600;
  color: var(--ink-500);
  margin-bottom: var(--space-2);
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.result-tag {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 12px;
  font-weight: 600;
  color: var(--brand-700);
  background: var(--brand-100);
  padding: 2px 8px;
  border-radius: var(--radius-full);
}

.image-frame {
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  overflow: hidden;
  background: var(--surface-1);
  aspect-ratio: 3 / 4;
  display: flex;
  align-items: center;
  justify-content: center;
}

.image-frame img {
  width: 100%;
  height: 100%;
  object-fit: contain;
}

.result-actions {
  display: flex;
  justify-content: center;
  margin-top: var(--space-6);
}

/* 错误 */
.error-section {
  text-align: center;
  padding: var(--space-5) var(--space-2);
}

.error-icon {
  color: var(--danger-500);
  margin-bottom: var(--space-3);
}

.error-section h2 {
  font-size: 22px;
}

.error-text {
  color: var(--ink-700);
  margin-top: var(--space-3);
  max-width: 460px;
  margin-left: auto;
  margin-right: auto;
}

.error-hint {
  color: var(--ink-500);
  font-size: 14px;
  margin-top: var(--space-2);
}

.error-actions {
  display: flex;
  justify-content: center;
  gap: var(--space-3);
  margin-top: var(--space-6);
}

@media (max-width: 640px) {
  .compare-grid {
    grid-template-columns: 1fr;
  }
  .lang-row {
    grid-template-columns: 1fr;
  }
  .lang-swap {
    justify-content: center;
    padding-bottom: 0;
  }
}
</style>

// frontend/src/components/TranslatePanel.jsx
import { Fragment, useEffect, useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import {
  UploadCloud,
  FileImage,
  X,
  ArrowRight,
  Wand2,
  Download,
  RotateCcw,
  RefreshCw,
  AlertTriangle,
  Check,
  Loader2,
  ChevronDown,
} from 'lucide-react'
import {
  createTranslateTask,
  getTaskStatus,
  getTaskResultUrl,
  deleteTask,
  formatBytes,
  formatDuration,
} from '../api'
import { useToast } from './Toast'
import CompareSlider from './CompareSlider'

const STEPS = [
  { key: 'detect', label: '检测区域', weight: 0.15 },
  { key: 'ocr', label: '识别文字', weight: 0.25 },
  { key: 'translate', label: '翻译', weight: 0.3 },
  { key: 'inpaint', label: '修复图像', weight: 0.15 },
  { key: 'render', label: '渲染译文', weight: 0.15 },
]

const ALLOWED = '.jpg,.jpeg,.png,.webp,.bmp'
const MAX_MB = 10

function stepIndexFromProgress(progress) {
  let acc = 0
  for (let i = 0; i < STEPS.length; i++) {
    acc += STEPS[i].weight * 100
    if (progress < acc) return i
  }
  return STEPS.length - 1
}

function validateFile(f) {
  if (!f) return '请选择图片文件'
  const ext = (f.name.split('.').pop() || '').toLowerCase()
  if (!ALLOWED.includes(`.${ext}`)) return `不支持 .${ext} 格式，仅支持 JPG / PNG / WebP / BMP`
  if (f.size > MAX_MB * 1024 * 1024) return `文件超过 ${MAX_MB}MB 限制，请压缩后重试`
  if (f.size === 0) return '文件为空'
  if (!f.type.startsWith('image/')) return '请上传图片文件'
  return ''
}

function LangSelect({ id, label, value, options, onChange }) {
  return (
    <label className="block">
      <span className="mb-2 block font-mono text-[10px] uppercase tracking-[0.25em] text-ink-500">
        {label}
      </span>
      <div className="relative">
        <select
          id={id}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="input-base appearance-none px-4 py-3 pr-10 font-medium"
        >
          {options.map((o) => (
            <option key={o.value} value={o.value} className="bg-surface-2">
              {o.label}
            </option>
          ))}
        </select>
        <ChevronDown
          size={16}
          className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-ink-500"
        />
      </div>
    </label>
  )
}

const panelMotion = {
  initial: { opacity: 0, y: 24 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -16 },
  transition: { type: 'spring', stiffness: 200, damping: 24 },
}

export default function TranslatePanel() {
  const notify = useToast()

  const [phase, setPhase] = useState('idle') // idle | submitting | running | result | error
  const [file, setFile] = useState(null)
  const [filePreviewUrl, setFilePreviewUrl] = useState('')
  const [fileError, setFileError] = useState('')
  const [isDragging, setIsDragging] = useState(false)
  const [sourceLang, setSourceLang] = useState('ja')
  const [targetLang, setTargetLang] = useState('zh')

  const [taskId, setTaskId] = useState(null)
  const [progress, setProgress] = useState(0)
  const [result, setResult] = useState(null)
  const [errorMessage, setErrorMessage] = useState('')

  const inputRef = useRef(null)
  const pollRef = useRef(null)
  const fileRef = useRef(null)

  useEffect(() => () => stopPolling(), [])
  useEffect(() => () => {
    if (filePreviewUrl) URL.revokeObjectURL(filePreviewUrl)
  }, [filePreviewUrl])

  const currentStep = useMemo(
    () => (phase === 'running' ? stepIndexFromProgress(progress) : -1),
    [phase, progress],
  )

  function stopPolling() {
    if (pollRef.current) {
      clearInterval(pollRef.current)
      pollRef.current = null
    }
  }

  function setFile0(f) {
    const err = validateFile(f)
    setFileError(err)
    if (err) {
      setFile(null)
      setFilePreviewUrl('')
      return false
    }
    fileRef.current = f
    setFile(f)
    setFilePreviewUrl(URL.createObjectURL(f))
    return true
  }

  function onFileSelect(e) {
    const f = e.target.files?.[0]
    if (f) setFile0(f)
    e.target.value = ''
  }

  function onDrop(e) {
    e.preventDefault()
    setIsDragging(false)
    const f = e.dataTransfer.files?.[0]
    if (f) setFile0(f)
  }

  function clearFile() {
    setFile(null)
    setFilePreviewUrl('')
    setFileError('')
    fileRef.current = null
  }

  function startTranslate() {
    if (!file) return
    const f = file
    setPhase('submitting')
    setFileError('')
    setErrorMessage('')
    setResult(null)
    setProgress(0)

    createTranslateTask(f, sourceLang, targetLang)
      .then((data) => {
        setTaskId(data.task_id)
        setPhase('running')
        startPolling(data.task_id)
      })
      .catch((err) => {
        setPhase('error')
        setErrorMessage(err.message)
        notify(err.message, 'error')
      })
  }

  function startPolling(id) {
    stopPolling()
    const tick = () => pollStatus(id)
    pollRef.current = setInterval(tick, 800)
    tick()
  }

  async function pollStatus(id) {
    try {
      const status = await getTaskStatus(id)
      setProgress(Math.max(progress, status.progress || 0))
      if (status.status === 'completed') {
        stopPolling()
        setResult({
          resultUrl: getTaskResultUrl(id),
          originalUrl: filePreviewUrl,
          textCount: status.text_count,
          durationMs: status.duration_ms,
        })
        setPhase('result')
        notify('翻译完成', 'success')
      } else if (status.status === 'failed') {
        stopPolling()
        setErrorMessage(status.error || '翻译失败，请重试')
        setPhase('error')
        notify(status.error || '翻译失败', 'error')
      }
    } catch (err) {
      stopPolling()
      setErrorMessage(err.message)
      setPhase('error')
      notify('获取进度失败：' + err.message, 'error')
    }
  }

  function cancelTask() {
    stopPolling()
    if (taskId) deleteTask(taskId).catch(() => {})
    resetAll()
  }

  function resetAll() {
    stopPolling()
    setTaskId(null)
    setProgress(0)
    setErrorMessage('')
    setResult(null)
    setPhase('idle')
  }

  const isBlurHint = (errorMessage || '').includes('模糊')

  return (
    <div className="card relative mx-auto max-w-[760px] p-8 md:p-10">
      <AnimatePresence mode="wait">
        {phase === 'idle' && (
          <motion.div key="idle" {...panelMotion}>
            <StepHeading index="01" title="上传漫画图片" />
            <Dropzone
              file={file}
              previewUrl={filePreviewUrl}
              isDragging={isDragging}
              setIsDragging={setIsDragging}
              onDrop={onDrop}
              onSelect={onFileSelect}
              onClear={clearFile}
              inputRef={inputRef}
            />
            {fileError && (
              <motion.p
                initial={{ opacity: 0, y: -6 }}
                animate={{ opacity: 1, y: 0 }}
                className="mt-3 flex items-center gap-2 text-sm text-danger"
                role="alert"
              >
                <AlertTriangle size={15} />
                {fileError}
              </motion.p>
            )}

            <StepHeading index="02" title="选择翻译方向" className="mt-9" />
            <div className="grid grid-cols-[1fr_auto_1fr] items-end gap-4">
              <LangSelect
                id="source-lang"
                label="Source"
                value={sourceLang}
                onChange={setSourceLang}
                options={[
                  { value: 'ja', label: '日语' },
                  { value: 'en', label: '英语' },
                ]}
              />
              <div className="flex h-[50px] items-center justify-center text-ink-500">
                <ArrowRight size={18} />
              </div>
              <LangSelect
                id="target-lang"
                label="Target"
                value={targetLang}
                onChange={setTargetLang}
                options={[{ value: 'zh', label: '中文' }]}
              />
            </div>

            <div className="mt-9 flex justify-center">
              <PrimaryButton
                disabled={!file}
                onClick={startTranslate}
                icon={<Wand2 size={18} />}
                label="开始翻译"
              />
            </div>
          </motion.div>
        )}

        {phase === 'submitting' && (
          <motion.div key="submitting" {...panelMotion} className="py-10 text-center">
            <Loader2 size={28} className="mx-auto animate-spin text-accent" />
            <p className="mt-4 text-ink-200">正在提交任务…</p>
          </motion.div>
        )}

        {phase === 'running' && (
          <motion.div key="running" {...panelMotion}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Loader2 size={20} className="animate-spin text-accent" />
                <h2 className="font-display text-xl font-semibold">正在翻译漫画</h2>
              </div>
              <span className="font-mono text-sm text-ink-400">{progress}%</span>
            </div>
            <p className="mt-1 truncate text-sm text-ink-500">{file?.name}</p>

            <div className="mt-8 h-1.5 overflow-hidden rounded-full bg-surface-2">
              <motion.div
                className="h-full rounded-full bg-gradient-to-r from-accent-strong to-accent"
                animate={{ width: `${progress}%` }}
                transition={{ type: 'spring', stiffness: 120, damping: 24 }}
              />
            </div>

            <Pipeline currentStep={currentStep} progress={progress} />

            <div className="mt-8 flex justify-center">
              <button
                onClick={cancelTask}
                className="rounded-lg border border-line px-5 py-2.5 text-sm text-ink-400 transition-colors hover:border-danger/40 hover:text-danger"
              >
                取消翻译
              </button>
            </div>
          </motion.div>
        )}

        {phase === 'result' && result && (
          <motion.div key="result" {...panelMotion}>
            <div className="mb-6 flex flex-wrap items-end justify-between gap-4">
              <div>
                <h2 className="font-display text-xl font-semibold text-ink-100">翻译完成</h2>
                <p className="mt-1 text-sm text-ink-500">
                  共识别 {result.textCount} 处文字
                  {result.durationMs ? ` · 耗时 ${formatDuration(result.durationMs)}` : ''}
                </p>
              </div>
              <a
                href={result.resultUrl}
                download
                className="group flex items-center gap-2 rounded-lg bg-gradient-to-r from-accent-strong to-accent px-5 py-2.5 text-sm font-medium text-bg shadow-[0_0_24px_-8px_rgba(34,211,238,0.7)] transition-transform hover:scale-[1.03]"
              >
                <Download size={16} />
                下载图片
              </a>
            </div>

            <CompareSlider before={result.originalUrl} after={result.resultUrl} />

            <p className="mt-4 text-center font-mono text-[11px] uppercase tracking-[0.2em] text-ink-600">
              拖动滑块对比原图与译文
            </p>

            <div className="mt-6 flex justify-center">
              <button
                onClick={resetAll}
                className="flex items-center gap-2 rounded-lg border border-line px-5 py-2.5 text-sm text-ink-200 transition-colors hover:border-accent/40 hover:text-accent"
              >
                <RotateCcw size={16} />
                翻译下一张
              </button>
            </div>
          </motion.div>
        )}

        {phase === 'error' && (
          <motion.div key="error" {...panelMotion} className="py-8 text-center">
            <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-danger/30 bg-danger/10 text-danger">
              <AlertTriangle size={26} />
            </div>
            <h2 className="mt-5 font-display text-xl font-semibold">翻译失败</h2>
            <p className="mx-auto mt-3 max-w-md text-sm leading-relaxed text-ink-400">{errorMessage}</p>
            {isBlurHint && (
              <p className="mt-2 text-sm text-ink-500">建议：尝试更换更清晰、对比度更高的图片。</p>
            )}
            <div className="mt-8 flex justify-center gap-3">
              <button
                onClick={resetAll}
                className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-accent-strong to-accent px-5 py-2.5 text-sm font-medium text-bg transition-transform hover:scale-[1.03]"
              >
                <RefreshCw size={16} />
                重新上传
              </button>
              <button
                onClick={startTranslate}
                disabled={!file}
                className="rounded-lg border border-line px-5 py-2.5 text-sm text-ink-200 transition-colors hover:border-accent/40 hover:text-accent disabled:opacity-40"
              >
                重试
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

function StepHeading({ index, title, className = '' }) {
  return (
    <div className={`mb-5 flex items-center gap-3 ${className}`}>
      <span className="flex h-7 w-7 items-center justify-center rounded-md border border-accent/30 bg-accent/10 font-mono text-xs font-medium text-accent">
        {index}
      </span>
      <h2 className="font-display text-lg font-medium text-ink-100">{title}</h2>
    </div>
  )
}

function Dropzone({ file, previewUrl, isDragging, setIsDragging, onDrop, onSelect, onClear, inputRef }) {
  return (
    <div
      className={`relative cursor-pointer overflow-hidden rounded-xl border-2 border-dashed transition-all duration-200 ${
        isDragging
          ? 'border-accent bg-accent/[0.06] ring-glow'
          : 'border-line-strong bg-surface-2/40 hover:border-accent/40 hover:bg-surface-2/70'
      }`}
      onDragOver={(e) => {
        e.preventDefault()
        setIsDragging(true)
      }}
      onDragLeave={(e) => {
        e.preventDefault()
        setIsDragging(false)
      }}
      onDrop={onDrop}
      onClick={() => inputRef.current?.click()}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault()
          inputRef.current?.click()
        }
      }}
    >
      <input
        ref={inputRef}
        type="file"
        accept={ALLOWED}
        className="hidden"
        onChange={onSelect}
      />

      {!file ? (
        <div className="flex flex-col items-center justify-center px-6 py-14 text-center">
          <motion.div
            animate={isDragging ? { y: -6, scale: 1.05 } : { y: 0, scale: 1 }}
            className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl border border-line bg-surface text-accent"
          >
            <UploadCloud size={26} />
          </motion.div>
          <p className="text-[15px] font-medium text-ink-100">点击上传，或拖拽图片到此处</p>
          <p className="mt-2 text-[13px] text-ink-500">支持 JPG / PNG / WebP / BMP · 单张不超过 10MB</p>
        </div>
      ) : (
        <div className="flex items-center gap-5 px-6 py-6">
          <div className="h-20 w-20 shrink-0 overflow-hidden rounded-lg border border-line bg-surface-2">
            <img src={previewUrl} alt="待翻译图片预览" className="h-full w-full object-cover" />
          </div>
          <div className="min-w-0 flex-1 text-left">
            <p className="truncate text-[15px] font-medium text-ink-100">{file.name}</p>
            <p className="mt-1 text-[13px] text-ink-500">{formatBytes(file.size)}</p>
          </div>
          <button
            onClick={(e) => {
              e.stopPropagation()
              onClear()
            }}
            className="flex h-9 w-9 items-center justify-center rounded-lg text-ink-500 transition-colors hover:bg-surface hover:text-danger"
            aria-label="移除图片"
          >
            <X size={18} />
          </button>
        </div>
      )}
    </div>
  )
}

function PrimaryButton({ disabled, onClick, icon, label }) {
  return (
    <motion.button
      whileHover={disabled ? undefined : { scale: 1.02 }}
      whileTap={disabled ? undefined : { scale: 0.98 }}
      onClick={onClick}
      disabled={disabled}
      className={`flex items-center gap-2.5 rounded-xl px-12 py-4 text-[15px] font-medium transition-all ${
        disabled
          ? 'cursor-not-allowed bg-surface-2 text-ink-600'
          : 'bg-gradient-to-r from-accent-strong to-accent text-bg shadow-[0_8px_32px_-8px_rgba(34,211,238,0.6)] hover:shadow-[0_8px_40px_-6px_rgba(34,211,238,0.8)]'
      }`}
    >
      {icon}
      {label}
    </motion.button>
  )
}

function Pipeline({ currentStep, progress }) {
  return (
    <div className="mt-8">
      <div className="flex items-center">
        {STEPS.map((s, i) => {
          const done = i < currentStep
          const active = i === currentStep
          return (
            <Fragment key={s.key}>
              {i > 0 && (
                <div className="relative h-px flex-1 overflow-hidden bg-line-strong">
                  <motion.div
                    className="absolute inset-y-0 left-0 bg-accent"
                    initial={false}
                    animate={{ width: i <= currentStep ? '100%' : '0%' }}
                    transition={{ duration: 0.5 }}
                  />
                </div>
              )}
              <div className="flex flex-col items-center gap-2">
                <motion.span
                  animate={
                    active
                      ? { boxShadow: ['0 0 0 0 rgba(34,211,238,0.4)', '0 0 0 8px rgba(34,211,238,0)'] }
                      : {}
                  }
                  transition={{ duration: 1.6, repeat: active ? Infinity : 0, ease: 'easeOut' }}
                  className={`flex h-9 w-9 items-center justify-center rounded-full border text-xs font-medium transition-colors ${
                    done
                      ? 'border-accent bg-accent text-bg'
                      : active
                        ? 'border-accent bg-accent/15 text-accent'
                        : 'border-line-strong bg-surface-2 text-ink-600'
                  }`}
                >
                  {done ? <Check size={16} /> : <span className="font-mono">{i + 1}</span>}
                </motion.span>
                <span
                  className={`font-mono text-[10px] uppercase tracking-wider ${
                    active ? 'text-accent' : done ? 'text-ink-200' : 'text-ink-600'
                  }`}
                >
                  {s.label}
                </span>
              </div>
            </Fragment>
          )
        })}
      </div>
    </div>
  )
}
